parameters:
  webit_common_unit.unit_loader.class: Webit\Common\UnitBundle\PHPCR\UnitLoader
  webit_common_unit.unit_manager.class: Webit\Common\UnitBundle\PHPCR\UnitManager

services:
  webit_common_unit.unit_loader:
    class: %webit_common_unit.unit_loader.class%
    public: false
    arguments: [@doctrine_phpcr.odm.default_document_manager, %kernel.cache_dir%/units]
  webit_common_unit.unit_manager:
    class: %webit_common_unit.unit_manager.class%
    arguments: [@doctrine_phpcr.odm.default_document_manager, @webit_common_unit.unit_provider, %webit_common_unit.units_root_path%]
